#pragma once

#include <parser/parser.tab.h>

#ifndef yyFlexLexerOnce
#include <FlexLexer.h>
#endif

#include <istream>
#include <string>

namespace jgolang {

class Scanner : public yyFlexLexer {
public:
    // Reads from input; filename is used in token locations and diagnostics.
    Scanner(std::istream& input, const std::string& filename);

    // Returns the next token code (0 for EOF) and fills its value and location
    // for Bison. Converts numeric conversion errors to syntax_error.
    int lex(Parser::semantic_type* value, Parser::location_type* location);

private:
    // Generated by Flex from lexer.l; rules write the token value to value_.
    int yylex() override;

    // Converts internal Flex errors to exceptions handled by the parser.
    void LexerError(const char* message) override;
    
    // Called via YY_USER_ACTION before each Flex rule, including skipped
    // whitespace and comments; updates the location range's lines and columns.
    void advanceLocation(const char* text, int length);
    
    // Throws syntax_error at the current location instead of exiting the process.
    [[noreturn]] void fail(const std::string& message) const;

    std::string filename_;
    Parser::semantic_type* value_ = nullptr;
    Parser::location_type location_;
    Parser::location_type literalLocation_;

    std::string stringLiteral;
    std::string currentComment;
    int32_t runeValue = 0;
    long long currentInteger = 0;
    double floatingPoint = 0;
};

} // namespace jgolang
